repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: ['--branch', 'main']
    - id: check-added-large-files
      args: ['--maxkb=2000']
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
